<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            // 1. Admin user
            [
                'title' => 'Mr',
                'first_name' => 'Max',
                'surname' => 'Fotherby',
                'contact_address' => '1 Admin Street, Northampton',
                'contact_telephone_number' => '07123456789',
                'contact_email' => 'admin@example.com',
                'email' => 'admin@example.com',
                'phone' => '07123456789',
                'buyer_approved_status' => true,
                'bank_account_no' => '12345678',
                'bank_sort_code' => '12-34-56',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'name',
                'role' => 'admin',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 2. Staff user
            [
                'title' => 'Ms',
                'first_name' => 'Jane',
                'surname' => 'Doe',
                'contact_address' => '10 Staff Lane, Northampton',
                'contact_telephone_number' => '07234567890',
                'contact_email' => 'jane.doe@example.com',
                'email' => 'jane.doe@example.com',
                'phone' => '07234567890',
                'buyer_approved_status' => false,
                'bank_account_no' => '87654321',
                'bank_sort_code' => '65-43-21',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'anonymous',
                'role' => 'staff',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 3. Customer user
            [
                'title' => 'Mr',
                'first_name' => 'John',
                'surname' => 'Smith',
                'contact_address' => '5 Customer Road, Northampton',
                'contact_telephone_number' => '07345678901',
                'contact_email' => 'john.smith@example.com',
                'email' => 'john.smith@example.com',
                'phone' => '07345678901',
                'buyer_approved_status' => true,
                'bank_account_no' => '23456789',
                'bank_sort_code' => '23-45-67',
                'customer_consent_profile' => false,
                'auction_display_setting' => 'business',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Mr',
                'first_name' => 'Tom',
                'surname' => 'Brown',
                'contact_address' => '12 Example Street, Northampton',
                'contact_telephone_number' => '07456789012',
                'contact_email' => 'tom.brown@example.com',
                'email' => 'tom.brown@example.com',
                'phone' => '07456789012',
                'buyer_approved_status' => true,
                'bank_account_no' => '34567890',
                'bank_sort_code' => '34-56-78',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'name',
                'role' => 'staff',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ms',
                'first_name' => 'Emily',
                'surname' => 'Clark',
                'contact_address' => '34 Example Lane, Northampton',
                'contact_telephone_number' => '07567890123',
                'contact_email' => 'emily.clark@example.com',
                'email' => 'emily.clark@example.com',
                'phone' => '07567890123',
                'buyer_approved_status' => true,
                'bank_account_no' => '45678901',
                'bank_sort_code' => '45-67-89',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'anonymous',
                'role' => 'staff',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr',
                'first_name' => 'David',
                'surname' => 'Taylor',
                'contact_address' => '56 Example Road, Northampton',
                'contact_telephone_number' => '07678901234',
                'contact_email' => 'david.taylor@example.com',
                'email' => 'david.taylor@example.com',
                'phone' => '07678901234',
                'buyer_approved_status' => true,
                'bank_account_no' => '56789012',
                'bank_sort_code' => '56-78-90',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'business',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ms',
                'first_name' => 'Sophia',
                'surname' => 'Green',
                'contact_address' => '78 Example Avenue, Northampton',
                'contact_telephone_number' => '07789012345',
                'contact_email' => 'sophia.green@example.com',
                'email' => 'sophia.green@example.com',
                'phone' => '07789012345',
                'buyer_approved_status' => false,
                'bank_account_no' => '67890123',
                'bank_sort_code' => '67-89-01',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'name',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr',
                'first_name' => 'Oliver',
                'surname' => 'White',
                'contact_address' => '90 Example Blvd, Northampton',
                'contact_telephone_number' => '07890123456',
                'contact_email' => 'oliver.white@example.com',
                'email' => 'oliver.white@example.com',
                'phone' => '07890123456',
                'buyer_approved_status' => true,
                'bank_account_no' => '78901234',
                'bank_sort_code' => '78-90-12',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'anonymous',
                'role' => 'staff',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ms',
                'first_name' => 'Chloe',
                'surname' => 'Adams',
                'contact_address' => '102 Example Street, Northampton',
                'contact_telephone_number' => '07901234567',
                'contact_email' => 'chloe.adams@example.com',
                'email' => 'chloe.adams@example.com',
                'phone' => '07901234567',
                'buyer_approved_status' => true,
                'bank_account_no' => '89012345',
                'bank_sort_code' => '89-01-23',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'business',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr',
                'first_name' => 'Liam',
                'surname' => 'Hall',
                'contact_address' => '114 Example Lane, Northampton',
                'contact_telephone_number' => '07012345678',
                'contact_email' => 'liam.hall@example.com',
                'email' => 'liam.hall@example.com',
                'phone' => '07012345678',
                'buyer_approved_status' => false,
                'bank_account_no' => '90123456',
                'bank_sort_code' => '90-12-34',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'name',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ms',
                'first_name' => 'Grace',
                'surname' => 'Lewis',
                'contact_address' => '126 Example Road, Northampton',
                'contact_telephone_number' => '07123456789',
                'contact_email' => 'grace.lewis@example.com',
                'email' => 'grace.lewis@example.com',
                'phone' => '07123456789',
                'buyer_approved_status' => true,
                'bank_account_no' => '01234567',
                'bank_sort_code' => '01-23-45',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'anonymous',
                'role' => 'staff',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr',
                'first_name' => 'Ethan',
                'surname' => 'Scott',
                'contact_address' => '138 Example Avenue, Northampton',
                'contact_telephone_number' => '07234567890',
                'contact_email' => 'ethan.scott@example.com',
                'email' => 'ethan.scott@example.com',
                'phone' => '07234567890',
                'buyer_approved_status' => true,
                'bank_account_no' => '12345678',
                'bank_sort_code' => '12-34-56',
                'customer_consent_profile' => true,
                'auction_display_setting' => 'business',
                'role' => 'customer',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
